#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.ReportData.Wss.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GDOC")]
	public partial class GEDOCSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTB_SesionTabla(TB_SesionTabla instance);
    partial void UpdateTB_SesionTabla(TB_SesionTabla instance);
    partial void DeleteTB_SesionTabla(TB_SesionTabla instance);
    partial void InsertTB_SesionTablaDetalle(TB_SesionTablaDetalle instance);
    partial void UpdateTB_SesionTablaDetalle(TB_SesionTablaDetalle instance);
    partial void DeleteTB_SesionTablaDetalle(TB_SesionTablaDetalle instance);
    partial void InsertTB_Log(TB_Log instance);
    partial void UpdateTB_Log(TB_Log instance);
    partial void DeleteTB_Log(TB_Log instance);
    #endregion
		
		public GEDOCSQLDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GDOCConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GEDOCSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GEDOCSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GEDOCSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GEDOCSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TB_SesionTabla> TB_SesionTablas
		{
			get
			{
				return this.GetTable<TB_SesionTabla>();
			}
		}
		
		public System.Data.Linq.Table<TB_SesionTablaDetalle> TB_SesionTablaDetalles
		{
			get
			{
				return this.GetTable<TB_SesionTablaDetalle>();
			}
		}
		
		public System.Data.Linq.Table<TB_Log> TB_Logs
		{
			get
			{
				return this.GetTable<TB_Log>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_SesionTabla")]
	public partial class TB_SesionTabla : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Sesion_Id;
		
		private string _Nombre;
		
		private int _UnidadTecnica_Id;
		
		private string _CreadoPor;
		
		private System.DateTime _FechaCreacion;
		
		private EntitySet<TB_SesionTablaDetalle> _TB_SesionTablaDetalles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSesion_IdChanging(int value);
    partial void OnSesion_IdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnUnidadTecnica_IdChanging(int value);
    partial void OnUnidadTecnica_IdChanged();
    partial void OnCreadoPorChanging(string value);
    partial void OnCreadoPorChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    #endregion
		
		public TB_SesionTabla()
		{
			this._TB_SesionTablaDetalles = new EntitySet<TB_SesionTablaDetalle>(new Action<TB_SesionTablaDetalle>(this.attach_TB_SesionTablaDetalles), new Action<TB_SesionTablaDetalle>(this.detach_TB_SesionTablaDetalles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sesion_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Sesion_Id
		{
			get
			{
				return this._Sesion_Id;
			}
			set
			{
				if ((this._Sesion_Id != value))
				{
					this.OnSesion_IdChanging(value);
					this.SendPropertyChanging();
					this._Sesion_Id = value;
					this.SendPropertyChanged("Sesion_Id");
					this.OnSesion_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadTecnica_Id", DbType="Int NOT NULL")]
		public int UnidadTecnica_Id
		{
			get
			{
				return this._UnidadTecnica_Id;
			}
			set
			{
				if ((this._UnidadTecnica_Id != value))
				{
					this.OnUnidadTecnica_IdChanging(value);
					this.SendPropertyChanging();
					this._UnidadTecnica_Id = value;
					this.SendPropertyChanged("UnidadTecnica_Id");
					this.OnUnidadTecnica_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this.OnCreadoPorChanging(value);
					this.SendPropertyChanging();
					this._CreadoPor = value;
					this.SendPropertyChanged("CreadoPor");
					this.OnCreadoPorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SesionTabla_TB_SesionTablaDetalle", Storage="_TB_SesionTablaDetalles", ThisKey="Sesion_Id", OtherKey="Sesion_Id")]
		public EntitySet<TB_SesionTablaDetalle> TB_SesionTablaDetalles
		{
			get
			{
				return this._TB_SesionTablaDetalles;
			}
			set
			{
				this._TB_SesionTablaDetalles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_SesionTablaDetalles(TB_SesionTablaDetalle entity)
		{
			this.SendPropertyChanging();
			entity.TB_SesionTabla = this;
		}
		
		private void detach_TB_SesionTablaDetalles(TB_SesionTablaDetalle entity)
		{
			this.SendPropertyChanging();
			entity.TB_SesionTabla = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_SesionTablaDetalle")]
	public partial class TB_SesionTablaDetalle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SesionDetalle_Id;
		
		private int _Sesion_Id;
		
		private int _Requerimento_Id;
		
		private string _DocumentoIngreso;
		
		private EntityRef<TB_SesionTabla> _TB_SesionTabla;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSesionDetalle_IdChanging(int value);
    partial void OnSesionDetalle_IdChanged();
    partial void OnSesion_IdChanging(int value);
    partial void OnSesion_IdChanged();
    partial void OnRequerimento_IdChanging(int value);
    partial void OnRequerimento_IdChanged();
    partial void OnDocumentoIngresoChanging(string value);
    partial void OnDocumentoIngresoChanged();
    #endregion
		
		public TB_SesionTablaDetalle()
		{
			this._TB_SesionTabla = default(EntityRef<TB_SesionTabla>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SesionDetalle_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SesionDetalle_Id
		{
			get
			{
				return this._SesionDetalle_Id;
			}
			set
			{
				if ((this._SesionDetalle_Id != value))
				{
					this.OnSesionDetalle_IdChanging(value);
					this.SendPropertyChanging();
					this._SesionDetalle_Id = value;
					this.SendPropertyChanged("SesionDetalle_Id");
					this.OnSesionDetalle_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sesion_Id", DbType="Int NOT NULL")]
		public int Sesion_Id
		{
			get
			{
				return this._Sesion_Id;
			}
			set
			{
				if ((this._Sesion_Id != value))
				{
					if (this._TB_SesionTabla.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSesion_IdChanging(value);
					this.SendPropertyChanging();
					this._Sesion_Id = value;
					this.SendPropertyChanged("Sesion_Id");
					this.OnSesion_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Requerimento_Id", DbType="Int NOT NULL")]
		public int Requerimento_Id
		{
			get
			{
				return this._Requerimento_Id;
			}
			set
			{
				if ((this._Requerimento_Id != value))
				{
					this.OnRequerimento_IdChanging(value);
					this.SendPropertyChanging();
					this._Requerimento_Id = value;
					this.SendPropertyChanged("Requerimento_Id");
					this.OnRequerimento_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentoIngreso", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string DocumentoIngreso
		{
			get
			{
				return this._DocumentoIngreso;
			}
			set
			{
				if ((this._DocumentoIngreso != value))
				{
					this.OnDocumentoIngresoChanging(value);
					this.SendPropertyChanging();
					this._DocumentoIngreso = value;
					this.SendPropertyChanged("DocumentoIngreso");
					this.OnDocumentoIngresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SesionTabla_TB_SesionTablaDetalle", Storage="_TB_SesionTabla", ThisKey="Sesion_Id", OtherKey="Sesion_Id", IsForeignKey=true)]
		public TB_SesionTabla TB_SesionTabla
		{
			get
			{
				return this._TB_SesionTabla.Entity;
			}
			set
			{
				TB_SesionTabla previousValue = this._TB_SesionTabla.Entity;
				if (((previousValue != value) 
							|| (this._TB_SesionTabla.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_SesionTabla.Entity = null;
						previousValue.TB_SesionTablaDetalles.Remove(this);
					}
					this._TB_SesionTabla.Entity = value;
					if ((value != null))
					{
						value.TB_SesionTablaDetalles.Add(this);
						this._Sesion_Id = value.Sesion_Id;
					}
					else
					{
						this._Sesion_Id = default(int);
					}
					this.SendPropertyChanged("TB_SesionTabla");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Log")]
	public partial class TB_Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Log;
		
		private string _Formulario;
		
		private string _Accion;
		
		private string _Estado;
		
		private string _Etapa;
		
		private System.DateTime _Fecha;
		
		private string _Usuario;
		
		private string _DocumentoIngreso;
		
		private string _DireccionIp;
		
		private string _NombrePc;
		
		private string _UserAgent;
		
		private string _ExtraData;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_LogChanging(int value);
    partial void OnId_LogChanged();
    partial void OnFormularioChanging(string value);
    partial void OnFormularioChanged();
    partial void OnAccionChanging(string value);
    partial void OnAccionChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnEtapaChanging(string value);
    partial void OnEtapaChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnDocumentoIngresoChanging(string value);
    partial void OnDocumentoIngresoChanged();
    partial void OnDireccionIpChanging(string value);
    partial void OnDireccionIpChanged();
    partial void OnNombrePcChanging(string value);
    partial void OnNombrePcChanged();
    partial void OnUserAgentChanging(string value);
    partial void OnUserAgentChanged();
    partial void OnExtraDataChanging(string value);
    partial void OnExtraDataChanged();
    #endregion
		
		public TB_Log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Log", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Log
		{
			get
			{
				return this._Id_Log;
			}
			set
			{
				if ((this._Id_Log != value))
				{
					this.OnId_LogChanging(value);
					this.SendPropertyChanging();
					this._Id_Log = value;
					this.SendPropertyChanged("Id_Log");
					this.OnId_LogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Formulario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Formulario
		{
			get
			{
				return this._Formulario;
			}
			set
			{
				if ((this._Formulario != value))
				{
					this.OnFormularioChanging(value);
					this.SendPropertyChanging();
					this._Formulario = value;
					this.SendPropertyChanged("Formulario");
					this.OnFormularioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accion", DbType="VarChar(30)")]
		public string Accion
		{
			get
			{
				return this._Accion;
			}
			set
			{
				if ((this._Accion != value))
				{
					this.OnAccionChanging(value);
					this.SendPropertyChanging();
					this._Accion = value;
					this.SendPropertyChanged("Accion");
					this.OnAccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etapa", DbType="VarChar(50)")]
		public string Etapa
		{
			get
			{
				return this._Etapa;
			}
			set
			{
				if ((this._Etapa != value))
				{
					this.OnEtapaChanging(value);
					this.SendPropertyChanging();
					this._Etapa = value;
					this.SendPropertyChanged("Etapa");
					this.OnEtapaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentoIngreso", DbType="VarChar(100)")]
		public string DocumentoIngreso
		{
			get
			{
				return this._DocumentoIngreso;
			}
			set
			{
				if ((this._DocumentoIngreso != value))
				{
					this.OnDocumentoIngresoChanging(value);
					this.SendPropertyChanging();
					this._DocumentoIngreso = value;
					this.SendPropertyChanged("DocumentoIngreso");
					this.OnDocumentoIngresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DireccionIp", DbType="VarChar(50)")]
		public string DireccionIp
		{
			get
			{
				return this._DireccionIp;
			}
			set
			{
				if ((this._DireccionIp != value))
				{
					this.OnDireccionIpChanging(value);
					this.SendPropertyChanging();
					this._DireccionIp = value;
					this.SendPropertyChanged("DireccionIp");
					this.OnDireccionIpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombrePc", DbType="VarChar(500)")]
		public string NombrePc
		{
			get
			{
				return this._NombrePc;
			}
			set
			{
				if ((this._NombrePc != value))
				{
					this.OnNombrePcChanging(value);
					this.SendPropertyChanging();
					this._NombrePc = value;
					this.SendPropertyChanged("NombrePc");
					this.OnNombrePcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAgent", DbType="VarChar(500)")]
		public string UserAgent
		{
			get
			{
				return this._UserAgent;
			}
			set
			{
				if ((this._UserAgent != value))
				{
					this.OnUserAgentChanging(value);
					this.SendPropertyChanging();
					this._UserAgent = value;
					this.SendPropertyChanged("UserAgent");
					this.OnUserAgentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtraData", DbType="VarChar(2000)")]
		public string ExtraData
		{
			get
			{
				return this._ExtraData;
			}
			set
			{
				if ((this._ExtraData != value))
				{
					this.OnExtraDataChanging(value);
					this.SendPropertyChanging();
					this._ExtraData = value;
					this.SendPropertyChanged("ExtraData");
					this.OnExtraDataChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
