//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.Service.WsSso {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Identidad", Namespace="http://www.dibam.cl")]
    [System.SerializableAttribute()]
    public partial class Identidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AtributoADField;
        
        private bool LogeadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AtributoAD {
            get {
                return this.AtributoADField;
            }
            set {
                if ((object.ReferenceEquals(this.AtributoADField, value) != true)) {
                    this.AtributoADField = value;
                    this.RaisePropertyChanged("AtributoAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Logeado {
            get {
                return this.LogeadoField;
            }
            set {
                if ((this.LogeadoField.Equals(value) != true)) {
                    this.LogeadoField = value;
                    this.RaisePropertyChanged("Logeado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dibam.cl", ConfigurationName="WsSso.WSSOSoap")]
    public interface WSSOSoap {
        
        // CODEGEN: Generating message contract since element name token from namespace http://www.dibam.cl is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dibam.cl/SystemValidate", ReplyAction="*")]
        Gedoc.Service.WsSso.SystemValidateResponse SystemValidate(Gedoc.Service.WsSso.SystemValidateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dibam.cl/SystemValidate", ReplyAction="*")]
        System.Threading.Tasks.Task<Gedoc.Service.WsSso.SystemValidateResponse> SystemValidateAsync(Gedoc.Service.WsSso.SystemValidateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SystemValidateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SystemValidate", Namespace="http://www.dibam.cl", Order=0)]
        public Gedoc.Service.WsSso.SystemValidateRequestBody Body;
        
        public SystemValidateRequest() {
        }
        
        public SystemValidateRequest(Gedoc.Service.WsSso.SystemValidateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dibam.cl")]
    public partial class SystemValidateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int SistemaID;
        
        public SystemValidateRequestBody() {
        }
        
        public SystemValidateRequestBody(string token, int SistemaID) {
            this.token = token;
            this.SistemaID = SistemaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SystemValidateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SystemValidateResponse", Namespace="http://www.dibam.cl", Order=0)]
        public Gedoc.Service.WsSso.SystemValidateResponseBody Body;
        
        public SystemValidateResponse() {
        }
        
        public SystemValidateResponse(Gedoc.Service.WsSso.SystemValidateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dibam.cl")]
    public partial class SystemValidateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Gedoc.Service.WsSso.Identidad SystemValidateResult;
        
        public SystemValidateResponseBody() {
        }
        
        public SystemValidateResponseBody(Gedoc.Service.WsSso.Identidad SystemValidateResult) {
            this.SystemValidateResult = SystemValidateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSOSoapChannel : Gedoc.Service.WsSso.WSSOSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSOSoapClient : System.ServiceModel.ClientBase<Gedoc.Service.WsSso.WSSOSoap>, Gedoc.Service.WsSso.WSSOSoap {
        
        public WSSOSoapClient() {
        }
        
        public WSSOSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSOSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSOSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSOSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gedoc.Service.WsSso.SystemValidateResponse Gedoc.Service.WsSso.WSSOSoap.SystemValidate(Gedoc.Service.WsSso.SystemValidateRequest request) {
            return base.Channel.SystemValidate(request);
        }
        
        public Gedoc.Service.WsSso.Identidad SystemValidate(string token, int SistemaID) {
            Gedoc.Service.WsSso.SystemValidateRequest inValue = new Gedoc.Service.WsSso.SystemValidateRequest();
            inValue.Body = new Gedoc.Service.WsSso.SystemValidateRequestBody();
            inValue.Body.token = token;
            inValue.Body.SistemaID = SistemaID;
            Gedoc.Service.WsSso.SystemValidateResponse retVal = ((Gedoc.Service.WsSso.WSSOSoap)(this)).SystemValidate(inValue);
            return retVal.Body.SystemValidateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gedoc.Service.WsSso.SystemValidateResponse> Gedoc.Service.WsSso.WSSOSoap.SystemValidateAsync(Gedoc.Service.WsSso.SystemValidateRequest request) {
            return base.Channel.SystemValidateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gedoc.Service.WsSso.SystemValidateResponse> SystemValidateAsync(string token, int SistemaID) {
            Gedoc.Service.WsSso.SystemValidateRequest inValue = new Gedoc.Service.WsSso.SystemValidateRequest();
            inValue.Body = new Gedoc.Service.WsSso.SystemValidateRequestBody();
            inValue.Body.token = token;
            inValue.Body.SistemaID = SistemaID;
            return ((Gedoc.Service.WsSso.WSSOSoap)(this)).SystemValidateAsync(inValue);
        }
    }
}
