//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.WebApp.WssRegMonSrvReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonumentoDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MonumentoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenominacionOficialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsoActualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtrasDenominacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gedoc.WebApp.WssRegMonSrvReference.CategoriaMonumentoDto CategoriaMonumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gedoc.WebApp.WssRegMonSrvReference.AgrupadorDto[] AgrupadoresField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gedoc.WebApp.WssRegMonSrvReference.GrillaDto[] GrillasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gedoc.WebApp.WssRegMonSrvReference.CarpetaDto[] AdjuntosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DenominacionOficial {
            get {
                return this.DenominacionOficialField;
            }
            set {
                if ((object.ReferenceEquals(this.DenominacionOficialField, value) != true)) {
                    this.DenominacionOficialField = value;
                    this.RaisePropertyChanged("DenominacionOficial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreUsoActual {
            get {
                return this.NombreUsoActualField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsoActualField, value) != true)) {
                    this.NombreUsoActualField = value;
                    this.RaisePropertyChanged("NombreUsoActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string OtrasDenominaciones {
            get {
                return this.OtrasDenominacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.OtrasDenominacionesField, value) != true)) {
                    this.OtrasDenominacionesField = value;
                    this.RaisePropertyChanged("OtrasDenominaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Gedoc.WebApp.WssRegMonSrvReference.CategoriaMonumentoDto CategoriaMonumento {
            get {
                return this.CategoriaMonumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaMonumentoField, value) != true)) {
                    this.CategoriaMonumentoField = value;
                    this.RaisePropertyChanged("CategoriaMonumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Gedoc.WebApp.WssRegMonSrvReference.AgrupadorDto[] Agrupadores {
            get {
                return this.AgrupadoresField;
            }
            set {
                if ((object.ReferenceEquals(this.AgrupadoresField, value) != true)) {
                    this.AgrupadoresField = value;
                    this.RaisePropertyChanged("Agrupadores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public Gedoc.WebApp.WssRegMonSrvReference.GrillaDto[] Grillas {
            get {
                return this.GrillasField;
            }
            set {
                if ((object.ReferenceEquals(this.GrillasField, value) != true)) {
                    this.GrillasField = value;
                    this.RaisePropertyChanged("Grillas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public Gedoc.WebApp.WssRegMonSrvReference.CarpetaDto[] Adjuntos {
            get {
                return this.AdjuntosField;
            }
            set {
                if ((object.ReferenceEquals(this.AdjuntosField, value) != true)) {
                    this.AdjuntosField = value;
                    this.RaisePropertyChanged("Adjuntos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaMonumentoDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CategoriaMonumentoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCortoField;
        
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreCorto {
            get {
                return this.NombreCortoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCortoField, value) != true)) {
                    this.NombreCortoField = value;
                    this.RaisePropertyChanged("NombreCorto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgrupadorDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AgrupadorDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gedoc.WebApp.WssRegMonSrvReference.ValorCampoDto[] ValoresField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUnicoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Gedoc.WebApp.WssRegMonSrvReference.ValorCampoDto[] Valores {
            get {
                return this.ValoresField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoresField, value) != true)) {
                    this.ValoresField = value;
                    this.RaisePropertyChanged("Valores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NombreUnico {
            get {
                return this.NombreUnicoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUnicoField, value) != true)) {
                    this.NombreUnicoField = value;
                    this.RaisePropertyChanged("NombreUnico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GrillaDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GrillaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUnicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gedoc.WebApp.WssRegMonSrvReference.FilaGrillaDto[] FilasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreUnico {
            get {
                return this.NombreUnicoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUnicoField, value) != true)) {
                    this.NombreUnicoField = value;
                    this.RaisePropertyChanged("NombreUnico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Gedoc.WebApp.WssRegMonSrvReference.FilaGrillaDto[] Filas {
            get {
                return this.FilasField;
            }
            set {
                if ((object.ReferenceEquals(this.FilasField, value) != true)) {
                    this.FilasField = value;
                    this.RaisePropertyChanged("Filas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarpetaDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CarpetaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUnicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gedoc.WebApp.WssRegMonSrvReference.ArchivoDto[] ArchivosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreUnico {
            get {
                return this.NombreUnicoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUnicoField, value) != true)) {
                    this.NombreUnicoField = value;
                    this.RaisePropertyChanged("NombreUnico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Gedoc.WebApp.WssRegMonSrvReference.ArchivoDto[] Archivos {
            get {
                return this.ArchivosField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivosField, value) != true)) {
                    this.ArchivosField = value;
                    this.RaisePropertyChanged("Archivos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValorCampoDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ValorCampoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUnicoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NombreUnico {
            get {
                return this.NombreUnicoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUnicoField, value) != true)) {
                    this.NombreUnicoField = value;
                    this.RaisePropertyChanged("NombreUnico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilaGrillaDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FilaGrillaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int LineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gedoc.WebApp.WssRegMonSrvReference.ValorCampoDto[] ValoresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Linea {
            get {
                return this.LineaField;
            }
            set {
                if ((this.LineaField.Equals(value) != true)) {
                    this.LineaField = value;
                    this.RaisePropertyChanged("Linea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Gedoc.WebApp.WssRegMonSrvReference.ValorCampoDto[] Valores {
            get {
                return this.ValoresField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoresField, value) != true)) {
                    this.ValoresField = value;
                    this.RaisePropertyChanged("Valores");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchivoDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ArchivoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gedoc.WebApp.WssRegMonSrvReference.ValorCampoDto[] MetadataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreArchivo {
            get {
                return this.NombreArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreArchivoField, value) != true)) {
                    this.NombreArchivoField = value;
                    this.RaisePropertyChanged("NombreArchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Gedoc.WebApp.WssRegMonSrvReference.ValorCampoDto[] Metadata {
            get {
                return this.MetadataField;
            }
            set {
                if ((object.ReferenceEquals(this.MetadataField, value) != true)) {
                    this.MetadataField = value;
                    this.RaisePropertyChanged("Metadata");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WssRegMonSrvReference.MonumentoServiceSoap")]
    public interface MonumentoServiceSoap {
        
        // CODEGEN: Generating message contract since element name codigo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar", ReplyAction="*")]
        Gedoc.WebApp.WssRegMonSrvReference.ConsultarResponse Consultar(Gedoc.WebApp.WssRegMonSrvReference.ConsultarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<Gedoc.WebApp.WssRegMonSrvReference.ConsultarResponse> ConsultarAsync(Gedoc.WebApp.WssRegMonSrvReference.ConsultarRequest request);
        
        // CODEGEN: Generating message contract since element name ListarResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        Gedoc.WebApp.WssRegMonSrvReference.ListarResponse Listar(Gedoc.WebApp.WssRegMonSrvReference.ListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<Gedoc.WebApp.WssRegMonSrvReference.ListarResponse> ListarAsync(Gedoc.WebApp.WssRegMonSrvReference.ListarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consultar", Namespace="http://tempuri.org/", Order=0)]
        public Gedoc.WebApp.WssRegMonSrvReference.ConsultarRequestBody Body;
        
        public ConsultarRequest() {
        }
        
        public ConsultarRequest(Gedoc.WebApp.WssRegMonSrvReference.ConsultarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigo;
        
        public ConsultarRequestBody() {
        }
        
        public ConsultarRequestBody(string codigo) {
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Gedoc.WebApp.WssRegMonSrvReference.ConsultarResponseBody Body;
        
        public ConsultarResponse() {
        }
        
        public ConsultarResponse(Gedoc.WebApp.WssRegMonSrvReference.ConsultarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Gedoc.WebApp.WssRegMonSrvReference.MonumentoDto ConsultarResult;
        
        public ConsultarResponseBody() {
        }
        
        public ConsultarResponseBody(Gedoc.WebApp.WssRegMonSrvReference.MonumentoDto ConsultarResult) {
            this.ConsultarResult = ConsultarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Listar", Namespace="http://tempuri.org/", Order=0)]
        public Gedoc.WebApp.WssRegMonSrvReference.ListarRequestBody Body;
        
        public ListarRequest() {
        }
        
        public ListarRequest(Gedoc.WebApp.WssRegMonSrvReference.ListarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarRequestBody {
        
        public ListarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Gedoc.WebApp.WssRegMonSrvReference.ListarResponseBody Body;
        
        public ListarResponse() {
        }
        
        public ListarResponse(Gedoc.WebApp.WssRegMonSrvReference.ListarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Gedoc.WebApp.WssRegMonSrvReference.MonumentoDto[] ListarResult;
        
        public ListarResponseBody() {
        }
        
        public ListarResponseBody(Gedoc.WebApp.WssRegMonSrvReference.MonumentoDto[] ListarResult) {
            this.ListarResult = ListarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MonumentoServiceSoapChannel : Gedoc.WebApp.WssRegMonSrvReference.MonumentoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonumentoServiceSoapClient : System.ServiceModel.ClientBase<Gedoc.WebApp.WssRegMonSrvReference.MonumentoServiceSoap>, Gedoc.WebApp.WssRegMonSrvReference.MonumentoServiceSoap {
        
        public MonumentoServiceSoapClient() {
        }
        
        public MonumentoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonumentoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonumentoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonumentoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gedoc.WebApp.WssRegMonSrvReference.ConsultarResponse Gedoc.WebApp.WssRegMonSrvReference.MonumentoServiceSoap.Consultar(Gedoc.WebApp.WssRegMonSrvReference.ConsultarRequest request) {
            return base.Channel.Consultar(request);
        }
        
        public Gedoc.WebApp.WssRegMonSrvReference.MonumentoDto Consultar(string codigo) {
            Gedoc.WebApp.WssRegMonSrvReference.ConsultarRequest inValue = new Gedoc.WebApp.WssRegMonSrvReference.ConsultarRequest();
            inValue.Body = new Gedoc.WebApp.WssRegMonSrvReference.ConsultarRequestBody();
            inValue.Body.codigo = codigo;
            Gedoc.WebApp.WssRegMonSrvReference.ConsultarResponse retVal = ((Gedoc.WebApp.WssRegMonSrvReference.MonumentoServiceSoap)(this)).Consultar(inValue);
            return retVal.Body.ConsultarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gedoc.WebApp.WssRegMonSrvReference.ConsultarResponse> Gedoc.WebApp.WssRegMonSrvReference.MonumentoServiceSoap.ConsultarAsync(Gedoc.WebApp.WssRegMonSrvReference.ConsultarRequest request) {
            return base.Channel.ConsultarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gedoc.WebApp.WssRegMonSrvReference.ConsultarResponse> ConsultarAsync(string codigo) {
            Gedoc.WebApp.WssRegMonSrvReference.ConsultarRequest inValue = new Gedoc.WebApp.WssRegMonSrvReference.ConsultarRequest();
            inValue.Body = new Gedoc.WebApp.WssRegMonSrvReference.ConsultarRequestBody();
            inValue.Body.codigo = codigo;
            return ((Gedoc.WebApp.WssRegMonSrvReference.MonumentoServiceSoap)(this)).ConsultarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gedoc.WebApp.WssRegMonSrvReference.ListarResponse Gedoc.WebApp.WssRegMonSrvReference.MonumentoServiceSoap.Listar(Gedoc.WebApp.WssRegMonSrvReference.ListarRequest request) {
            return base.Channel.Listar(request);
        }
        
        public Gedoc.WebApp.WssRegMonSrvReference.MonumentoDto[] Listar() {
            Gedoc.WebApp.WssRegMonSrvReference.ListarRequest inValue = new Gedoc.WebApp.WssRegMonSrvReference.ListarRequest();
            inValue.Body = new Gedoc.WebApp.WssRegMonSrvReference.ListarRequestBody();
            Gedoc.WebApp.WssRegMonSrvReference.ListarResponse retVal = ((Gedoc.WebApp.WssRegMonSrvReference.MonumentoServiceSoap)(this)).Listar(inValue);
            return retVal.Body.ListarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gedoc.WebApp.WssRegMonSrvReference.ListarResponse> Gedoc.WebApp.WssRegMonSrvReference.MonumentoServiceSoap.ListarAsync(Gedoc.WebApp.WssRegMonSrvReference.ListarRequest request) {
            return base.Channel.ListarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gedoc.WebApp.WssRegMonSrvReference.ListarResponse> ListarAsync() {
            Gedoc.WebApp.WssRegMonSrvReference.ListarRequest inValue = new Gedoc.WebApp.WssRegMonSrvReference.ListarRequest();
            inValue.Body = new Gedoc.WebApp.WssRegMonSrvReference.ListarRequestBody();
            return ((Gedoc.WebApp.WssRegMonSrvReference.MonumentoServiceSoap)(this)).ListarAsync(inValue);
        }
    }
}
