//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.Repositorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccionBandeja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccionBandeja()
        {
            this.AccionesPermitidasBandejas = new HashSet<AccionesPermitidasBandejas>();
            this.Rol = new HashSet<Rol>();
            this.AccionesPermitidasBandejaOficio = new HashSet<AccionesPermitidasBandejaOficio>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Icono { get; set; }
        public string Hint { get; set; }
        public string TipoAccion { get; set; }
        public int Orden { get; set; }
        public string IdAccion { get; set; }
        public string Onclick { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccionesPermitidasBandejas> AccionesPermitidasBandejas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rol> Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccionesPermitidasBandejaOficio> AccionesPermitidasBandejaOficio { get; set; }
    }
}
