//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.Repositorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccionesPermitidasBandejas
    {
        public int BandejaId { get; set; }
        public int EstadoId { get; set; }
        public int EtapaId { get; set; }
        public int AccionId { get; set; }
    
        public virtual AccionBandeja AccionBandeja { get; set; }
        public virtual BandejaEntrada BandejaEntrada { get; set; }
        public virtual EstadoRequerimiento EstadoRequerimiento { get; set; }
        public virtual EtapaRequerimiento EtapaRequerimiento { get; set; }
    }
}
