//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.Repositorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BandejaEntrada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BandejaEntrada()
        {
            this.AccionesPermitidasBandejas = new HashSet<AccionesPermitidasBandejas>();
            this.AccionesPermitidasBandejaOficio = new HashSet<AccionesPermitidasBandejaOficio>();
        }
    
        public int Id { get; set; }
        public int IdBandeja { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> DiasAtras { get; set; }
        public Nullable<int> CantRegistros { get; set; }
        public bool Habilitado { get; set; }
        public int Orden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccionesPermitidasBandejas> AccionesPermitidasBandejas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccionesPermitidasBandejaOficio> AccionesPermitidasBandejaOficio { get; set; }
    }
}
