//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.Repositorio.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GedocEntities : DbContext
    {
        public GedocEntities()
            : base("name=GedocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccionBandeja> AccionBandeja { get; set; }
        public virtual DbSet<AccionesPermitidasBandejas> AccionesPermitidasBandejas { get; set; }
        public virtual DbSet<Adjunto> Adjunto { get; set; }
        public virtual DbSet<BandejaEntrada> BandejaEntrada { get; set; }
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Caracter> Caracter { get; set; }
        public virtual DbSet<Caso> Caso { get; set; }
        public virtual DbSet<Despacho> Despacho { get; set; }
        public virtual DbSet<DespachoIniciativa> DespachoIniciativa { get; set; }
        public virtual DbSet<EstadoDespacho> EstadoDespacho { get; set; }
        public virtual DbSet<EstadoRegistro> EstadoRegistro { get; set; }
        public virtual DbSet<EstadoRequerimiento> EstadoRequerimiento { get; set; }
        public virtual DbSet<EtapaRequerimiento> EtapaRequerimiento { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<MonumentoNacional> MonumentoNacional { get; set; }
        public virtual DbSet<MotivoCierre> MotivoCierre { get; set; }
        public virtual DbSet<Remitente> Remitente { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<TipoTramite> TipoTramite { get; set; }
        public virtual DbSet<UnidadTecnica> UnidadTecnica { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<vw_AccionesBandeja> vw_AccionesBandeja { get; set; }
        public virtual DbSet<vw_BandejaEntradaDespachoInic> vw_BandejaEntradaDespachoInic { get; set; }
        public virtual DbSet<vw_Usuario> vw_Usuario { get; set; }
        public virtual DbSet<Reporte> Reporte { get; set; }
        public virtual DbSet<Requerimiento> Requerimiento { get; set; }
        public virtual DbSet<Correlativo> Correlativo { get; set; }
        public virtual DbSet<LogSistema> LogSistema { get; set; }
        public virtual DbSet<SesionTabla> SesionTabla { get; set; }
        public virtual DbSet<SesionTablaDetalle> SesionTablaDetalle { get; set; }
        public virtual DbSet<vw_BandejaEntrada> vw_BandejaEntrada { get; set; }
        public virtual DbSet<vw_FichaIngreso> vw_FichaIngreso { get; set; }
        public virtual DbSet<LogSistemaTexto> LogSistemaTexto { get; set; }
        public virtual DbSet<NotificacionEmail> NotificacionEmail { get; set; }
        public virtual DbSet<LogWssIntegracion> LogWssIntegracion { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<NotificacionEmailRegistro> NotificacionEmailRegistro { get; set; }
        public virtual DbSet<PlantillaOficio> PlantillaOficio { get; set; }
        public virtual DbSet<CampoPlantilla> CampoPlantilla { get; set; }
        public virtual DbSet<EstadoOficio> EstadoOficio { get; set; }
        public virtual DbSet<EtapaOficio> EtapaOficio { get; set; }
        public virtual DbSet<Oficio> Oficio { get; set; }
        public virtual DbSet<OficioObservacion> OficioObservacion { get; set; }
        public virtual DbSet<AccionesPermitidasBandejaOficio> AccionesPermitidasBandejaOficio { get; set; }
        public virtual DbSet<ReservaCorrelativo> ReservaCorrelativo { get; set; }
        public virtual DbSet<Lista> Lista { get; set; }
        public virtual DbSet<ListaValor> ListaValor { get; set; }
        public virtual DbSet<CalendarioBitacora> CalendarioBitacora { get; set; }
        public virtual DbSet<vw_EtiquetasReq> vw_EtiquetasReq { get; set; }
        public virtual DbSet<vw_GeneroReq> vw_GeneroReq { get; set; }
        public virtual DbSet<vw_RemitentesReq> vw_RemitentesReq { get; set; }
        public virtual DbSet<vw_GeneroReqNivel2> vw_GeneroReqNivel2 { get; set; }
        public virtual DbSet<vw_GeneroReqNivel1> vw_GeneroReqNivel1 { get; set; }
        public virtual DbSet<AdjuntoOficio> AdjuntoOficio { get; set; }
        public virtual DbSet<RemitenteRelacionBackup> RemitenteRelacionBackup { get; set; }
        public virtual DbSet<vw_DestinatarioDesp> vw_DestinatarioDesp { get; set; }
    
        public virtual ObjectResult<sp_DatosBandejaEntrada_Result> sp_DatosBandejaEntrada(Nullable<int> idBandeja)
        {
            var idBandejaParameter = idBandeja.HasValue ?
                new ObjectParameter("idBandeja", idBandeja) :
                new ObjectParameter("idBandeja", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DatosBandejaEntrada_Result>("sp_DatosBandejaEntrada", idBandejaParameter);
        }
    
        public virtual ObjectResult<sp_IngresosUltimos_Result> sp_IngresosUltimos(Nullable<int> diasAtras)
        {
            var diasAtrasParameter = diasAtras.HasValue ?
                new ObjectParameter("diasAtras", diasAtras) :
                new ObjectParameter("diasAtras", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_IngresosUltimos_Result>("sp_IngresosUltimos", diasAtrasParameter);
        }
    
        [DbFunction("GedocEntities", "SplitString")]
        public virtual IQueryable<SplitString_Result> SplitString(string text, string delimiter)
        {
            var textParameter = text != null ?
                new ObjectParameter("Text", text) :
                new ObjectParameter("Text", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitString_Result>("[GedocEntities].[SplitString](@Text, @Delimiter)", textParameter, delimiterParameter);
        }
    
        public virtual ObjectResult<SProcGetRoles_Result1> SProcGetRoles(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SProcGetRoles_Result1>("SProcGetRoles", userIdParameter);
        }
    
        public virtual ObjectResult<sp_DespachosUltimos_Result> sp_DespachosUltimos(Nullable<int> diasAtras)
        {
            var diasAtrasParameter = diasAtras.HasValue ?
                new ObjectParameter("diasAtras", diasAtras) :
                new ObjectParameter("diasAtras", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DespachosUltimos_Result>("sp_DespachosUltimos", diasAtrasParameter);
        }
    
        [DbFunction("GedocEntities", "fn_DiasNoHabiles_Table")]
        public virtual IQueryable<Nullable<System.DateTime>> fn_DiasNoHabiles_Table()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<System.DateTime>>("[GedocEntities].[fn_DiasNoHabiles_Table]()");
        }
    
        [DbFunction("GedocEntities", "fn_FechaDiasHabiles")]
        public virtual IQueryable<fn_FechaDiasHabiles_Result> fn_FechaDiasHabiles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_FechaDiasHabiles_Result>("[GedocEntities].[fn_FechaDiasHabiles]()");
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> sp_FechaDiasHabiles(Nullable<System.DateTime> fechaDesde, Nullable<int> diasContar)
        {
            var fechaDesdeParameter = fechaDesde.HasValue ?
                new ObjectParameter("fechaDesde", fechaDesde) :
                new ObjectParameter("fechaDesde", typeof(System.DateTime));
    
            var diasContarParameter = diasContar.HasValue ?
                new ObjectParameter("diasContar", diasContar) :
                new ObjectParameter("diasContar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("sp_FechaDiasHabiles", fechaDesdeParameter, diasContarParameter);
        }
    
        public virtual int sp_CambiaEstadoRemitente(string accion, Nullable<int> remitenteId, Nullable<int> usuarioId, string usuarioLoginName)
        {
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            var remitenteIdParameter = remitenteId.HasValue ?
                new ObjectParameter("remitenteId", remitenteId) :
                new ObjectParameter("remitenteId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("usuarioId", usuarioId) :
                new ObjectParameter("usuarioId", typeof(int));
    
            var usuarioLoginNameParameter = usuarioLoginName != null ?
                new ObjectParameter("usuarioLoginName", usuarioLoginName) :
                new ObjectParameter("usuarioLoginName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CambiaEstadoRemitente", accionParameter, remitenteIdParameter, usuarioIdParameter, usuarioLoginNameParameter);
        }
    }
}
