//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.Repositorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSistema
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Flujo { get; set; }
        public string Origen { get; set; }
        public string Accion { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<int> EtapaId { get; set; }
        public Nullable<int> RequerimientoId { get; set; }
        public string Usuario { get; set; }
        public string DireccionIp { get; set; }
        public string NombrePc { get; set; }
        public string UserAgent { get; set; }
        public string ExtraData { get; set; }
        public Nullable<int> OrigenId { get; set; }
        public Nullable<int> UnidadTecnicaId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<System.DateTime> OrigenFecha { get; set; }
    }
}
