//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.Repositorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSistemaTexto
    {
        public int Id { get; set; }
        public string Flujo { get; set; }
        public string Accion { get; set; }
        public string Actividad { get; set; }
        public string TextoBitacora { get; set; }
        public string Formulario { get; set; }
        public string TipoLog { get; set; }
    }
}
