//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.Repositorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogWssIntegracion
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int SolicitudTramId { get; set; }
        public Nullable<int> RequerimientoId { get; set; }
        public string Operacion { get; set; }
        public string Resultado { get; set; }
        public string Observaciones { get; set; }
    }
}
