//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.Repositorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonumentoNacional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonumentoNacional()
        {
            this.Requerimiento = new HashSet<Requerimiento>();
            this.DespachoIniciativa = new HashSet<DespachoIniciativa>();
            this.CategoriaMonumentoNac = new HashSet<ListaValor>();
            this.Comuna = new HashSet<ListaValor>();
            this.Provincia = new HashSet<ListaValor>();
            this.Region = new HashSet<ListaValor>();
        }
    
        public int Id { get; set; }
        public string DenominacionOficial { get; set; }
        public string OtrasDenominaciones { get; set; }
        public string NombreUsoActual { get; set; }
        public string DireccionMonumentoNac { get; set; }
        public string ReferenciaLocalidad { get; set; }
        public string RolSii { get; set; }
        public string CodigoMonumentoNac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requerimiento> Requerimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DespachoIniciativa> DespachoIniciativa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaValor> CategoriaMonumentoNac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaValor> Comuna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaValor> Provincia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaValor> Region { get; set; }
    }
}
