//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.Repositorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantillaOficio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlantillaOficio()
        {
            this.Oficio = new HashSet<Oficio>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> TipoTramiteId { get; set; }
        public string Contenido { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreacionId { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int UsuarioModificacionId { get; set; }
        public Nullable<System.DateTime> EliminacionFecha { get; set; }
        public Nullable<int> UsuarioEliminacionId { get; set; }
        public bool Eliminado { get; set; }
        public int TipoPlantillaId { get; set; }
        public bool TipoWord { get; set; }
        public string NombreDocumento { get; set; }
    
        public virtual TipoTramite TipoTramite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oficio> Oficio { get; set; }
        public virtual Usuario UsuarioCreacion { get; set; }
        public virtual Usuario UsuarioEliminacion { get; set; }
        public virtual Usuario UsuarioEdicion { get; set; }
    }
}
