//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.Repositorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemitenteRelacionBackup
    {
        public int Id { get; set; }
        public int RemitenteId { get; set; }
        public int OrigenId { get; set; }
        public string OrigenTipo { get; set; }
    }
}
