//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.Repositorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requerimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requerimiento()
        {
            this.Bitacora = new HashSet<Bitacora>();
            this.Despacho = new HashSet<Despacho>();
            this.UnidadTecnicaCopia = new HashSet<UnidadTecnica>();
            this.Caso1 = new HashSet<Caso>();
            this.SesionTablaDetalle = new HashSet<SesionTablaDetalle>();
            this.Despacho1 = new HashSet<Despacho>();
            this.Oficio = new HashSet<Oficio>();
            this.Etiqueta = new HashSet<ListaValor>();
            this.Soporte = new HashSet<ListaValor>();
            this.TipoAdjunto = new HashSet<ListaValor>();
            this.Adjunto = new HashSet<Adjunto>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> AdjuntaDocumentacion { get; set; }
        public Nullable<System.DateTime> AsignacionResponsable { get; set; }
        public Nullable<System.DateTime> AsignacionUt { get; set; }
        public Nullable<int> CantidadAdjuntos { get; set; }
        public Nullable<int> CaracterId { get; set; }
        public string ComentarioAsignacion { get; set; }
        public string ComentarioCierre { get; set; }
        public string ComentarioDevolucion { get; set; }
        public string ComentarioEncargadoUt { get; set; }
        public bool SoloMesAnno { get; set; }
        public string ProyectoActividad { get; set; }
        public bool DevolverIngresoCentral { get; set; }
        public string DocumentoIngreso { get; set; }
        public Nullable<System.DateTime> EnviadoUt { get; set; }
        public Nullable<bool> EnviarAsignacion { get; set; }
        public Nullable<bool> EnviarPriorizacion { get; set; }
        public Nullable<bool> EnviarUt { get; set; }
        public int EstadoId { get; set; }
        public int EtapaId { get; set; }
        public Nullable<System.DateTime> AsignacionAnterior { get; set; }
        public Nullable<System.DateTime> AsignacionProfesionalTemp { get; set; }
        public Nullable<System.DateTime> AsignacionUtTemp { get; set; }
        public Nullable<System.DateTime> Cierre { get; set; }
        public Nullable<System.DateTime> Devolucion { get; set; }
        public System.DateTime FechaDocumento { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaIngresoHistorico { get; set; }
        public Nullable<System.DateTime> Liberacion { get; set; }
        public Nullable<System.DateTime> RecepcionUt { get; set; }
        public Nullable<System.DateTime> Resolucion { get; set; }
        public Nullable<System.DateTime> RecepcionUtTemp { get; set; }
        public Nullable<bool> LiberarAsignacionTemp { get; set; }
        public string Materia { get; set; }
        public Nullable<int> MotivoCierreId { get; set; }
        public string NombreProyectoPrograma { get; set; }
        public int NumeroIngreso { get; set; }
        public string NumeroTicket { get; set; }
        public string ObservacionesTipoDoc { get; set; }
        public string ObservacionesAdjuntos { get; set; }
        public string ObservacionesFormaLlegada { get; set; }
        public string ObservacionesTransparencia { get; set; }
        public string ObservacionesCaracter { get; set; }
        public string ObservacionesHistorico { get; set; }
        public Nullable<int> Plazo { get; set; }
        public Nullable<int> ProfesionalId { get; set; }
        public Nullable<int> ProfesionalTranspId { get; set; }
        public Nullable<int> ProfesionalTempId { get; set; }
        public Nullable<bool> Redireccionado { get; set; }
        public Nullable<int> RemitenteId { get; set; }
        public Nullable<int> RequerimientoAnteriorId { get; set; }
        public string RequerimientoNoRegistrado { get; set; }
        public Nullable<bool> RequiereAcuerdo { get; set; }
        public Nullable<bool> RequiereRespuesta { get; set; }
        public Nullable<bool> RequiereTimbrajePlano { get; set; }
        public Nullable<int> ResponsableTranspId { get; set; }
        public Nullable<int> ResponsableUtId { get; set; }
        public Nullable<int> ResponsableUtTempId { get; set; }
        public Nullable<int> SolicitanteUrgenciaId { get; set; }
        public string TipoIngreso { get; set; }
        public Nullable<System.DateTime> FechaUltOficio { get; set; }
        public Nullable<int> UtAsignadaId { get; set; }
        public Nullable<int> UtApoyoId { get; set; }
        public Nullable<int> UtConocimientoId { get; set; }
        public Nullable<int> UtTemporalId { get; set; }
        public Nullable<int> UtAnteriorId { get; set; }
        public Nullable<int> UtTransparenciaId { get; set; }
        public Nullable<int> TipoTramiteId { get; set; }
        public int MonumentoNacionalId { get; set; }
        public Nullable<int> CasoId { get; set; }
        public string UltimoAcuerdoComision { get; set; }
        public string UltimoAcuerdoSesion { get; set; }
        public Nullable<System.DateTime> FechaUltAcuerdoComision { get; set; }
        public Nullable<System.DateTime> FechaUltAcuerdoSesion { get; set; }
        public Nullable<int> CerradoPorId { get; set; }
        public Nullable<int> UsuarioCreacionId { get; set; }
        public Nullable<int> UsuarioEliminacionId { get; set; }
        public Nullable<System.DateTime> EliminacionFecha { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<int> SolicitudTramId { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<bool> ForzarPrioridad { get; set; }
        public Nullable<System.DateTime> ForzarPrioridadFecha { get; set; }
        public string ForzarPrioridadMotivo { get; set; }
        public string CanalLlegadaTramiteCod { get; set; }
        public int CanalLlegadaTramiteListaId { get; set; }
        public string FormaLlegadaCod { get; set; }
        public int FormaLlegadaListaId { get; set; }
        public string PrioridadCod { get; set; }
        public string TipoDocumentoCod { get; set; }
        public int PrioridadListaId { get; set; }
        public int TipoDocumentoListaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bitacora> Bitacora { get; set; }
        public virtual Caracter Caracter { get; set; }
        public virtual Caso Caso { get; set; }
        public virtual EstadoRequerimiento EstadoRequerimiento { get; set; }
        public virtual EtapaRequerimiento EtapaRequerimiento { get; set; }
        public virtual MonumentoNacional MonumentoNacional { get; set; }
        public virtual MotivoCierre MotivoCierre { get; set; }
        public virtual Remitente Remitente { get; set; }
        public virtual Usuario SolicitanteUrgencia { get; set; }
        public virtual TipoTramite TipoTramite { get; set; }
        public virtual UnidadTecnica UnidadTecnicaAnterior { get; set; }
        public virtual UnidadTecnica UnidadTecnicaApoyo { get; set; }
        public virtual UnidadTecnica UnidadTecnicaAsign { get; set; }
        public virtual UnidadTecnica UnidadTecnicaConoc { get; set; }
        public virtual UnidadTecnica UnidadTecnicaTemp { get; set; }
        public virtual UnidadTecnica UnidadTecnicaTransp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Despacho> Despacho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnidadTecnica> UnidadTecnicaCopia { get; set; }
        public virtual Usuario UsuarioCreacion { get; set; }
        public virtual Usuario UsuarioEliminacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caso> Caso1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SesionTablaDetalle> SesionTablaDetalle { get; set; }
        public virtual Usuario ProfesionalUt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Despacho> Despacho1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oficio> Oficio { get; set; }
        public virtual ListaValor CanalLlegadaTramite { get; set; }
        public virtual ListaValor FormaLlegada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaValor> Etiqueta { get; set; }
        public virtual ListaValor Prioridad { get; set; }
        public virtual ListaValor TipoDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaValor> Soporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaValor> TipoAdjunto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adjunto> Adjunto { get; set; }
    }
}
