//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.Repositorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SesionTablaDetalle
    {
        public int Id { get; set; }
        public int SesionTablaId { get; set; }
        public int RequerimentoId { get; set; }
        public string DocumentoIngreso { get; set; }
    
        public virtual Requerimiento Requerimiento { get; set; }
        public virtual SesionTabla SesionTabla { get; set; }
    }
}
