//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.Repositorio.Model
{
    using System;
    
    public partial class SProcGetRoles_Result1
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public bool Activo { get; set; }
    }
}
