//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.Repositorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DestinatarioDesp
    {
        public string RequerimientoMainDocumentoIngreso { get; set; }
        public System.DateTime RequerimientoMainFechaIngreso { get; set; }
        public Nullable<int> RequerimientoUnidadTecnicaAsignId { get; set; }
        public string RequerimientoMainUnidadTecnicaAsignTitulo { get; set; }
        public Nullable<int> RequerimientoMainProfesionalId { get; set; }
        public string RequerimientoMainProfesionalNombre { get; set; }
        public string Materia { get; set; }
        public string DestinatarioNombre { get; set; }
        public string RequerimientoMainEtiquetaTitulos { get; set; }
        public string FolioDespacho { get; set; }
        public Nullable<System.DateTime> FechaEmisionOficio { get; set; }
        public string RequerimientoMainRegionTitulos { get; set; }
        public string RequerimientoMainComunaTitulos { get; set; }
        public string TipoAdjuntoTitulos { get; set; }
        public int EstadoId { get; set; }
        public string EstadoTitulo { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public string MedioDespachoCod { get; set; }
        public string MedioDespachoTitulo { get; set; }
        public string MedioVerificacionCod { get; set; }
        public string MedioVerificacionTitulo { get; set; }
        public string ObservacionesDespacho { get; set; }
        public string ObservacionesMedioVerif { get; set; }
        public Nullable<int> CasoId { get; set; }
        public string CasoTitulo { get; set; }
        public Nullable<int> TipoTramiteId { get; set; }
        public string TipoTramiteTitulo { get; set; }
        public string RequerimientoMainCanalLlegadaTramiteCod { get; set; }
        public string RequerimientoMainCanalLlegadaTramiteTitulo { get; set; }
        public string RequerimientoMainCategoriaMonumentoNacTitulo { get; set; }
        public string RequerimientoMainMonumentoNacionalDenominacionOficial { get; set; }
        public string RequerimientoMainMonumentoNacionalOtrasDenominaciones { get; set; }
        public string RequerimientoMainMonumentoNacionalNombreUsoActual { get; set; }
        public string RequerimientoMainMonumentoNacionalReferenciaLocalidad { get; set; }
    }
}
