//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gedoc.Repositorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FichaIngreso
    {
        public int Id { get; set; }
        public string DocumentoIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaDocumento { get; set; }
        public int EstadoId { get; set; }
        public string EstadoTitulo { get; set; }
        public int EtapaId { get; set; }
        public string EtapaTitulo { get; set; }
        public Nullable<int> TipoTramiteId { get; set; }
        public string TipoTramiteTitulo { get; set; }
        public string CanalLlegadaTramiteTitulo { get; set; }
        public string TipoDocumentoTitulo { get; set; }
        public string TipoIngreso { get; set; }
        public string ObservacionesTipoDoc { get; set; }
        public string FechasEmisionOficio { get; set; }
        public Nullable<bool> AdjuntaDocumentacion { get; set; }
        public Nullable<int> CantidadAdjuntos { get; set; }
        public string TipoAdjuntoTitulos { get; set; }
        public string SoporteTitulos { get; set; }
        public string ObservacionesAdjuntos { get; set; }
        public Nullable<int> RemitenteId { get; set; }
        public string RemitenteNombre { get; set; }
        public string RemitenteRut { get; set; }
        public string RemitenteGenero { get; set; }
        public string RemitenteCargo { get; set; }
        public string RemitenteInstitucion { get; set; }
        public string RemitenteTipoInstitucion { get; set; }
        public string RemitenteDireccion { get; set; }
        public string RemitenteEmail { get; set; }
        public string RemitenteTelefono { get; set; }
        public string NombreProyectoPrograma { get; set; }
        public string ProyectoActividad { get; set; }
        public Nullable<int> CasoId { get; set; }
        public string CasoTitulo { get; set; }
        public string Materia { get; set; }
        public int MonumentoNacionalId { get; set; }
        public string EtiquetaTitulos { get; set; }
        public string MonumentoNacionalCategoriaMonumentoNacCod { get; set; }
        public string MonumentoNacionalCodigoMonumentoNac { get; set; }
        public string MonumentoNacionalDenominacionOficial { get; set; }
        public string MonumentoNacionalOtrasDenominaciones { get; set; }
        public string MonumentoNacionalNombreUsoActual { get; set; }
        public string MonumentoNacionalDireccionMonumentoNac { get; set; }
        public string MonumentoNacionalReferenciaLocalidad { get; set; }
        public string MonumentoNacionalRegionTitulo { get; set; }
        public string MonumentoNacionalProvinciaTitulo { get; set; }
        public string MonumentoNacionalComunaTitulo { get; set; }
        public string MonumentoNacionalRolSii { get; set; }
        public string FormaLlegadaTitulo { get; set; }
        public string ObservacionesFormaLlegada { get; set; }
        public Nullable<bool> Redireccionado { get; set; }
        public string NumeroTicket { get; set; }
        public Nullable<bool> RequiereAcuerdo { get; set; }
        public Nullable<int> RequerimientoAnteriorId { get; set; }
        public string RequerimientoAnteriorDocIng { get; set; }
        public string RequerimientoNoRegistrado { get; set; }
        public Nullable<int> CaracterId { get; set; }
        public string CaracterTitulo { get; set; }
        public string ObservacionesCaracter { get; set; }
        public Nullable<System.DateTime> AsignacionAnterior { get; set; }
        public Nullable<int> UtAnteriorId { get; set; }
        public string UtAnteriorTitulo { get; set; }
        public Nullable<int> UtAsignadaId { get; set; }
        public string UtAsignadaTitulo { get; set; }
        public Nullable<System.DateTime> AsignacionUt { get; set; }
        public string UtCopiaTitulos { get; set; }
        public Nullable<int> UtConocimientoId { get; set; }
        public string UtConocimientoTitulo { get; set; }
        public Nullable<int> UtTemporalId { get; set; }
        public string UtTemporalTitulo { get; set; }
        public Nullable<bool> RequiereRespuesta { get; set; }
        public string ComentarioAsignacion { get; set; }
        public Nullable<int> UtApoyoId { get; set; }
        public string UtApoyoTitulo { get; set; }
        public Nullable<int> Plazo { get; set; }
        public string PrioridadTitulo { get; set; }
        public Nullable<int> SolicitanteUrgenciaId { get; set; }
        public string SolicitanteUrgenciaNombre { get; set; }
        public Nullable<System.DateTime> AsignacionUtTemp { get; set; }
        public Nullable<int> ResponsableUtTempId { get; set; }
        public string ResponsableUtTempNombresApellidos { get; set; }
        public Nullable<System.DateTime> RecepcionUtTemp { get; set; }
        public Nullable<int> ProfesionalTempId { get; set; }
        public string ProfesionalTempNombresApellidos { get; set; }
        public Nullable<System.DateTime> AsignacionProfesionalTemp { get; set; }
        public Nullable<System.DateTime> Liberacion { get; set; }
        public Nullable<int> UtTransparenciaId { get; set; }
        public string UtTransparenciaTitulo { get; set; }
        public Nullable<int> ProfesionalTranspId { get; set; }
        public string ProfesionalTranspNombresApellidos { get; set; }
        public string ObservacionesTransparencia { get; set; }
        public Nullable<int> ResponsableUtId { get; set; }
        public string ResponsableNombre { get; set; }
        public Nullable<System.DateTime> RecepcionUt { get; set; }
        public Nullable<int> ProfesionalId { get; set; }
        public string ProfesionalNombre { get; set; }
        public Nullable<System.DateTime> AsignacionResponsable { get; set; }
        public string ComentarioEncargadoUt { get; set; }
        public Nullable<bool> RequiereTimbrajePlano { get; set; }
        public Nullable<System.DateTime> Cierre { get; set; }
        public Nullable<int> CerradoPorId { get; set; }
        public string CerradoPor { get; set; }
        public Nullable<int> MotivoCierreId { get; set; }
        public string ComentarioCierre { get; set; }
        public Nullable<System.DateTime> ModificadoPorFecha { get; set; }
        public Nullable<int> SolicitudTramId { get; set; }
        public string MotivoCierreTitulo { get; set; }
        public Nullable<System.DateTime> Devolucion { get; set; }
        public Nullable<bool> ForzarPrioridad { get; set; }
        public Nullable<System.DateTime> ForzarPrioridadFecha { get; set; }
        public string ForzarPrioridadMotivo { get; set; }
        public string EncargadoEmail { get; set; }
        public string ProfesionalEmail { get; set; }
        public string CanalLlegadaTramiteCod { get; set; }
        public string TipoDocumentoCod { get; set; }
        public string FormaLlegadaCod { get; set; }
        public string PrioridadCod { get; set; }
    }
}
